version: "2"

services:
  prometheus:
    build: ./prometheus
    image: prometheus
    command: ./prometheus -alertmanager.url=http://alertmanager:9093
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - prom
    volumes:
      - ./prometheus/prometheus.yml:/prometheus/prometheus.yml
      - ./prometheus/alerts.rules:/prometheus/alerts.rules

  alertmanager:
    build: ./alertmanager
    image: alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    networks:
      - prom
    volumes:
      - ./alertmanager/alertmanager.yml:/alertmanager/alertmanager.yml

   grafana:
     image: grafana fg2it/grafana-armhf:v4.1.2
     ports:
       - 13000:3000
     environment:
       - GF_SECURITY_ADMIN_PASSWORD=admin
       - GF_AUTH_ANONYMOUS_ENABLED=true

  node_exporter:
    build: ./node-exporter
    image: node-exporter
    command: ./node_exporter -collector.procfs /host/proc -collector.sysfs /host/proc -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)" -collectors.enabled conntrack,diskstats,entropy,filefd,filesystem,loadavg,mdadm,meminfo,netdev,netstat,sockstat,stat,textfile,time,uname,vmstat
    container_name: node
    ports:
      - "9100:9100"
    networks:
      - prom
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs

   bmp085:
     build: ./bmp085
     image: bmp085
     container_name: bmp085
     ports:
       - "8080:8080"
     networks:
       - prom

networks:
  prom:
